---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: feign-client
  name: feign-client
spec:
  replicas: 1
  selector:
    matchLabels:
      run: feign-client
  template:
    metadata:
      labels:
        run: feign-client
        visualize: "true"
    spec:
      containers:
        - name: feign-client
          image: arthurstrokov/feign-client:v0.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVER-PORT
              value: "30001"
            - name: EUREKA-DEFAULT-ZONE
              value: "http://192.168.59.100:30003/eureka/"
            - name: EUREKA-INSTANCE-HOSTNAME
              value: "192.168.59.100"
          ports:
            - containerPort: 8282
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: feign-client
  name: feign-client
spec:
  selector:
    run: feign-client
  ports:
    - name: feign-client-port
      port: 30001
      protocol: TCP
      targetPort: 30001
      nodePort: 30001
  type: NodePort
