---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: feign-client
  name: feign-client
spec:
  replicas: 1
  selector:
    matchLabels:
      run: feign-client
  template:
    metadata:
      labels:
        run: feign-client
        visualize: "true"
    spec:
      containers:
        - name: feign-client
          image: arthurstrokov/feign-client:v0.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8282
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: feign-client
  name: feign-client
spec:
  selector:
    run: feign-client
  ports:
    - name: feign-client-port
      port: 8282
      protocol: TCP
      targetPort: 8282
      nodePort: 30006
  type: NodePort
