spring:
  main:
    banner-mode: off
  application:
    name: feign-client
---
eureka:
  client:
    service-url:
      defaultZone: http://192.168.59.106:30003/eureka/
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: false
#    hostname: 192.168.59.106
---
server:
  port: 8282
--- # Actuator
management:
  endpoints:
    web:
      exposure:
        include: ["*"]
