spring:
  main:
    banner-mode: off
  application:
    name: feign-client
---
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA-DEFAULT-ZONE:http://localhost:8761/eureka/}
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: false
    hostname: ${EUREKA-INSTANCE-HOSTNAME:localhost}
---
server:
  port: ${SERVER-PORT:8282}
--- # Actuator
management:
  endpoints:
    web:
      exposure:
        include: [ "*" ]
